### ISSUE TITLE
Compilation error on x86_64h-apple-darwin

### ISSUE THREAD

**Issue by NobodyXu** [rust-lang/cmake-rs#234]
https://github.com/cargo-bins/cargo-binstall/actions/runs/13194668463/job/36833691220#step:8:473

```
  CMake Error at /opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:129 (message):
    The C compiler targets architectures:

      "x86_64;x86_64h"

    but CMAKE_OSX_ARCHITECTURES is

      "x86_64"

  Call Stack (most recent call first):
    /opt/homebrew/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)
    CMakeLists.txt:37 (project)
``` 

cargo-bins/cargo-binstall#2036 error happens when bumping cc-rs from 1.2.10 to 1.2.12, however not sure if this is a cc-rs bug or cmake-rs bug, so I decided to open an issue here first

**Comment by NobodyXu** [comment]
cc 1.2.13 has fixed it related PR rust-lang/cc-rs#1389
